### ISSUE TITLE
Tocar música de fundo genérica 

### ISSUE THREAD

**Issue by laura-am06** [LMV-Jogos/Jogo#16]
Usar uma música da Internet sem restrições de direito autoral para tocar durante o jogo, mais especificamente uma por cena.

**Comment by marianakorb** [comment]
Para a trilha sonora de fundo foi escolhido [Crystal Cave](https://opengameart.org/content/crystal-cave-mysterious-ambience-seamless-loop)

**Comment by marianakorb** [comment]
A commit 76876bf9330fbe8c1670ecc84635ee4a012c3c40 atende a tarefa.
