### ISSUE TITLE
Publicar a versão v0.1 do jogo no GitHub Pages

### ISSUE THREAD

**Issue by laura-am06** [LMV-Jogos/Jogo#25]
Publicar o jogo em sua primeira versão experimental, v0.1, no GitHub Pages.

**Comment by laura-am06** [comment]
O que foi feito no jogo até o momento está rodando no servidor e disponível em https://lmv.boidacarapreta.cc/.

**Comment by ghost** [comment]
> O que foi feito no jogo até o momento está rodando no servidor e disponível em https://lmv.boidacarapreta.cc/.

Este link já se refere a tarefa #31. O link original, [para registro](https://lmv-jogos.github.io/Jogo/), já foi substituído por este novo.
