### ISSUE TITLE
Adicionar controles de teclado e/ou de *mouse* para o(s) personagem(ns)

### ISSUE THREAD

**Issue by laura-am06** [LMV-Jogos/Jogo#9]
Adicionar as teclas de teclado ou botões do mouse para movimentar o(s) personagem(ns) no cenário.

**Comment by vivianevalentina** [comment]
A commit 072b7d0ed823d7578191a23c7b2200c24d039aaa atende a tarefa, porém o personagem não move as pernas ao se mexer pra cima e pra baixo.
